language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'

deploy:
  provider: npm
  email: tadas@yoyo.lt
  api_key:
    secure: SbPn9NqQPT4Ki6BVknrbZVK2LdyoH5MNXaj2WVHamu/Fh2CHKcCXSvCw/0Ba6yWtei3IhEtCxsuy+jhkyoAoZvS19/kEb+3K1yXAVw9uMiM0F2wTZoA5mLzBvpYMm4SF3jlrsOsgh2yQktUSV6j/Wy5vGLiplbMPn2KIufSH4R8=
  on:
    tags: true
