language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'

deploy:
  provider: npm
  email: tadas@yoyo.lt
  api_key:
    secure: Ki5VxOx3PmoH3decxXHV+I26ppyB+WekKw7zioD31ubDv8/Bo2A06YCbmQg+1LuX4LN4/I2EfwrvpsIaDqQv1r4zpHMydJ1BG0sDw5aIjlibMUlov3n4lnwYGuRyhaWzmd/DQkP+UbIpJ67W+L3sI3jaxz8UC11HpPWINmyLHfk=
  on:
    tags: true
