name: Auto-update groups data

on:
  schedule:
    # Every first of the month at 10:00
    - cron:  '0 10 1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: npm ci --no-audit
      - run: npm test
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: npm ci --no-audit
      - run: npm run update-groups
      # See https://github.com/marketplace/actions/add-commit
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Auto-update groups
          author_email: devnull@inventaire.io
          message: 'Auto-update groups'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo 'Increment patch version number...'
          npm version patch
          echo 'Pushing commits to repo...'
          git push origin master
          echo 'Pushing tags to repo...'
          git push origin master --tags
          echo 'Setup .npmrc...'
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          echo 'Publish on NPM...'
          npm publish
          echo 'Done!'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
